#! /usr/bin/env bash

support_path=$(dirname $(which git-gpg))
source $support_path/global.bash
source $support_path/utils.bash
source $support_path/init.bash
source $support_path/hide.bash
source $support_path/reveal.bash
source $support_path/clean.bash
source $support_path/addperson.bash
source $support_path/whoknows.bash
source $support_path/diff.bash
source $support_path/burn.bash

case $1 in
  burn|whoknows|addperson|hide|init|diff|reveal|clean) $@;;
  *)
    echo "Invalid command $1"
    echo "$(basename $0) [burn|whoknows|addperson|hide|init|diff|reveal|clean]"
    exit 1;;
esac
