#! /usr/bin/env bash

support_path=$(dirname $(which git-gpg))
source $support_path/global.bash
source $support_path/utils.bash

source $support_path/init.bash
source $support_path/add-person.bash
source $support_path/hide.bash
source $support_path/reveal.bash
source $support_path/edit-key.bash
source $support_path/clean.bash
source $support_path/who-knows.bash
source $support_path/diff.bash
source $support_path/config.bash

_run () {
  for c in $commands; do
    if [[ $1 = $c  ]]; then
      $@
      exit 0
    fi
  done

  {
    echo "Invalid command"
    echo ""
    echo "Try one of the following:"
    echo ""

    for c in $commands; do
      echo "  $(tput bold)$(_${c}-signature)$(tput sgr0)"
      echo ""
      "_${c}-brief"
      echo ""
    done
  } | less -r
}

_run $@
